// src/utils/portfolioData.js
export const portfolioData = [
  {
    _id: '1',
    title: 'ZestMart E-Commerce Platform',
    description: 'A full-featured e-commerce platform with real-time inventory, payment gateway integration, and a custom admin panel. Built with MERN stack for a Kerala-based grocery chain.',
    category: 'Web',
    tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    imageGradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    accent: '#7c3aed',
    liveUrl: '#',
    featured: true,
  },
  {
    _id: '2',
    title: 'TechPulse SEO Campaign',
    description: 'Took a B2B SaaS startup from page 5 to #1 on Google for 12 target keywords within 4 months. Includes technical SEO audit, content strategy, and backlink building.',
    category: 'Marketing',
    tags: ['SEO', 'Content', 'Analytics', 'SEM'],
    imageGradient: 'linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)',
    accent: '#06b6d4',
    liveUrl: '#',
    featured: true,
  },
  {
    _id: '3',
    title: 'SmartHome Controller Hub',
    description: 'IoT-based home automation system using Raspberry Pi and MQTT protocol. Controls lighting, security cameras, temperature, and locks from a unified mobile dashboard.',
    category: 'IoT',
    tags: ['Raspberry Pi', 'MQTT', 'Python', 'React Native'],
    imageGradient: 'linear-gradient(135deg, #0a0a0a, #1a1a2e, #10b981)',
    accent: '#10b981',
    liveUrl: '#',
    featured: true,
  },
  {
    _id: '4',
    title: 'LegalEase Portfolio Website',
    description: 'Premium law firm portfolio with animated case studies section, multilingual support, and an integrated appointment booking system. Achieved 98 Google PageSpeed score.',
    category: 'Web',
    tags: ['Next.js', 'Tailwind', 'Framer Motion', 'i18n'],
    imageGradient: 'linear-gradient(135deg, #1c1c2e, #2d1b69, #11998e)',
    accent: '#9333ea',
    liveUrl: '#',
    featured: false,
  },
  {
    _id: '5',
    title: 'FoodieFlash Social Campaign',
    description: 'Instagram and Facebook growth campaign for a restaurant chain. 3x increase in followers, 5x engagement rate improvement, and 40% boost in online orders within 60 days.',
    category: 'Marketing',
    tags: ['Social Media', 'Meta Ads', 'Reels', 'Branding'],
    imageGradient: 'linear-gradient(135deg, #200122, #6f0000, #1a1a2e)',
    accent: '#f59e0b',
    liveUrl: '#',
    featured: false,
  },
  {
    _id: '6',
    title: 'AgroSense Field Monitor',
    description: 'Academic IoT project — wireless sensor network for real-time soil moisture, temperature, and pH monitoring. Alerts farmers via SMS and displays live data on a web dashboard.',
    category: 'IoT',
    tags: ['Arduino', 'ESP32', 'Firebase', 'React'],
    imageGradient: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
    accent: '#0ea5e9',
    liveUrl: '#',
    featured: false,
  },
  {
    _id: '7',
    title: 'ClinicBridge Patient Portal',
    description: 'Custom clinic management software with patient registration, appointment scheduling, billing, and digital prescription generation. Deployed across 3 clinics in Kerala.',
    category: 'IT',
    tags: ['React', 'Express', 'PostgreSQL', 'PDF Gen'],
    imageGradient: 'linear-gradient(135deg, #0d0d0d, #1a0533, #06b6d4)',
    accent: '#06b6d4',
    liveUrl: '#',
    featured: false,
  },
  {
    _id: '8',
    title: 'NexaBrand Identity System',
    description: 'Complete brand identity design and digital launch campaign for a fintech startup — logo, brand guidelines, landing page, and a targeted LinkedIn lead generation campaign.',
    category: 'Marketing',
    tags: ['Branding', 'Design', 'LinkedIn Ads', 'Figma'],
    imageGradient: 'linear-gradient(135deg, #1a1a2e, #4a0e8f, #e91e8c)',
    accent: '#c084fc',
    liveUrl: '#',
    featured: false,
  },
];

export const categories = ['All', 'Web', 'Marketing', 'IoT', 'IT'];
