// src/components/Team/TeamData.js
export const teamData = [
  {
    id: 1,
    name: 'Muhammed Lais M',
    role: 'Co-Founder & CEO',
    bio: 'Visionary leader driving Kodox\'s strategic growth. Passionate about leveraging technology to solve real-world problems.',
    color: '#7c3aed',
    initials: 'ML',
    social: { linkedin: '#', instagram: '#' },
  },
  {
    id: 2,
    name: 'Hadi Afnan',
    role: 'Co-Founder & CTO',
    bio: 'Full-stack architect and tech innovator. Expert in MERN stack, cloud infrastructure, and system design.',
    color: '#06b6d4',
    initials: 'HA',
    social: { linkedin: '#', github: '#' },
  },
  {
    id: 3,
    name: 'Eshan Sahad',
    role: 'Lead Developer',
    bio: 'Crafts pixel-perfect, high-performance web applications. Specializes in React.js and modern UI/UX engineering.',
    color: '#9333ea',
    initials: 'ES',
    social: { linkedin: '#', github: '#' },
  },
  {
    id: 4,
    name: 'Aswanth K P',
    role: 'Digital Marketing Head',
    bio: 'Growth hacker and data-driven marketer. Masters SEO, paid media, and conversion optimization strategies.',
    color: '#0ea5e9',
    initials: 'AK',
    social: { linkedin: '#', instagram: '#' },
  },
  {
    id: 5,
    name: 'Basith Rahman',
    role: 'IoT & Hardware Engineer',
    bio: 'Bridges the gap between physical and digital. Expert in embedded systems, Arduino, and industrial automation.',
    color: '#10b981',
    initials: 'BR',
    social: { linkedin: '#', github: '#' },
  },
  {
    id: 6,
    name: 'Mohammed Muntasir T',
    role: 'IT Solutions Specialist',
    bio: 'Enterprise IT expert and cloud architect. Designs robust, scalable infrastructure and custom software pipelines.',
    color: '#f59e0b',
    initials: 'MM',
    social: { linkedin: '#' },
  },
];
